# Evaluation prompts
knowledge_explanation: |
    你是一个有多年小学数学教学经验的标注员。我给你一段【输入文本】，这是数学教师给学生讲解知识点的文本。你依据【学生画像】【学生需求】，根据【标注规则】，从讲解语言、讲解策略、个性化三个维度，对文本进行评分。

    ##评分标准##
    每个-{评分点}-的满分是5分，你给出1-5的评分。

    ##评分标准##
    **讲解语言**：
    -角色贴合性-：符合教师身份，有一定专业性和权威性；不要尝试与用户进行动作互动；也不要尝试对教学方法或者教学原理进行介绍说明。 
    -语言流畅性-：语言清晰流畅；讲解文本充分，而不是简单逻辑框架；
    -语气温和-：语言温柔平和，语气不跳脱。
    **讲解策略**：
    -教学方法合理性-：使用的科学的教学方法，如支架式教学、引导式教学等；教学的步骤和逻辑合乎常理
    -内容设计合理性-：教学的引入、举例都符合学生的年级，不涉及超过学生认知阶段的知识或者物体、社会事件
    **个性化**：
    -用户特征呼应-：对学生的个人画像有所呼应，比如关注到他的年级、年龄或者他主动提出的兴趣爱好等其他个人信息。

    ##学生画像##
    {Student_image} 

    ##学生需求##
    {Student_query} 

    ##输入文本##
    {LLM_response}

    ##输出##
    你严格按照下文json格式输出，不要输出其他内容。
    {
        "角色贴合性":分数,
        "语言流畅性":分数,
        "语气温和":分数,
        "教学方法合理性":分数,
        "内容设计合理性":分数,
        "用户特征呼应":分数
    }



contextual_problem: |

    请你作为一名教育专家，基于以下评估指标，对给定的一道题目进行详细评估，并对每个子维度按李克特五点量表打分（1-5分，1分为“完全不符合”，5分为“完全符合”），并简要说明评分理由：
            一、题目内容质量
            1. 题目表述是否清晰易懂，避免了含糊或容易引起误解的表述
            2. 题目是否可解、存在正确解，对于单选题是否导向唯一答案
            3. 题目是否切实考察了所指定的知识点，符合课标要求
            4. 是否切实体现了教师所提及的核心素养要求
            5. 难度是否与教师指定难度大致一致
            二、答案与解析质量
            1. 答案是否准确，涵盖所有可能的正确答案
            2. 解析是否涵盖主流解题思路，紧扣当前知识点，无超纲内容
            3. 解析是否逻辑清晰、无明显跳跃，步骤合理
            三、题目情境质量
            1. 情境是否来源于现实生活，符合学生认知水平
            2. 情境是否与考察知识点融合成有机整体，而非割裂并置
            3. 情境表述是否规范、结构是否简洁清晰
            4. 情境故事是否符合社会主义核心价值观，不能违背“立德树人”精神

            请根据以下内容进行评估，主要评估生成题目的质量，模型回复的前后引导语不参与评估：
            教师要求：{prompt}
            模型回复：{query}
            请将最终结果严格以以下JSON格式输出，不得更改键名，score为该维度的得分，comment为你打分的理由，1-5分，1分为“完全不符合”，5分为“完全符合”，结构如下所示：
            {{
                "题目内容质量": {{
                    "题目表述清晰易懂": {{"score": 1, "comment": "在这里写你打分的理由"}},
                    "题目可解且有明确答案": {{"score": 5, "comment": "在这里写你打分的理由"}},
                    "考察知识点符合课标": {{"score": 4, "comment": "在这里写你打分的理由"}},
                    "体现核心素养": {{"score": 3, "comment": "在这里写你打分的理由"}},
                    "难度与教师要求一致": {{"score": 5, "comment": "在这里写你打分的理由"}},
                }},
                "答案解析质量": {{
                    "答案准确完整": {{"score": 5, "comment": "在这里写你打分的理由"}},
                    "解析思路主流、相关性强": {{"score": 4, "comment": "在这里写你打分的理由"}},
                    "解析逻辑清晰": {{"score": 5, "comment": "在这里写你打分的理由"}},
                }},
                "题目情境质量": {{
                    "情境贴近现实、符合认知": {{"score": 2, "comment": "在这里写你打分的理由"}},
                    "情境与知识融合": {{"score": 3, "comment": "在这里写你打分的理由"}},
                    "表述清晰结构简单": {{"score": 1, "comment": "在这里写你打分的理由"}},
                    "符合社会主义核心价值观": {{"score": 2, "comment": "在这里写你打分的理由"}}
                }}  
            }}

guided_teaching: |
  任务描述：
  你是一个教育领域专家，负责对师生教学对话进行专业评估。评估基于十个教学质量指标，每个指标采用5级量表评分(1-5分)。请保持评估的客观性、全面性和专业性，确保评分反映真实教学质量。
  
  评分标准：
  1分：完全不符合要求
  2分：基本不符合要求
  3分：一般
  4分：基本符合要求
  5分：完全符合要求
  
  评估指标及定义：
  1. 准确性
  定义：评估模型在讲解数学题时，其所阐述的数学知识（如概念、定理、公式、结论）与所展示的解题过程（如逻辑推理、演算步骤、方法运用、符号表达）是否均达到数学上的准确、严谨与规范。确保传递的信息内容无误，且分析、推导、计算的每一步都正确可靠，符合数学学科标准。
  正例：我们来计算这个长方形花坛的周长。长方形的周长公式是 (长 + 宽) × 2。所以，花坛的周长是 (8米 + 5米) × 2 = 13米 × 2 = 26米。
  反例：我们来计算这个长方形花坛的周长。长方形的周长是 长 × 宽。所以，花坛的周长是 8米 × 5米 = 40米。
  
  2. 个性化
  定义：评估模型是否能识别学生在当前数学问题上的知识基础、理解程度和卡点，并据此动态调整讲解的深度、节奏和方式。这包括：能否用学生易于理解的语言或类比解释抽象数学概念；能否设计恰当的追问或提示，启发学生独立思考而非直接给出答案；能否根据学生的具体错误提供有针对性的反馈和纠正路径。
  正例：学生：老师，我还是不太明白为什么负负得正。 老师：嗯，我明白了，这是很多同学初学时都会困惑的点。我们可以换个角度想：'减去一个负数'，就好比'取消一个债务'。比如，你欠了小明5元钱(债务是-5元)，如果我帮你'取消了这个债务'(减去-5元)，是不是相当于你的钱增加了5元呢？所以 -(-5) 就等于 +5。你觉得这个例子好理解一些吗？或者你之前尝试过用数轴来理解吗？
  反例：学生：老师，我还是不太明白为什么负负得正。 老师：这是一个基本运算法则，记住就行了：负负得正。我们继续看下一题。
  
  3. 元认知培养
  定义：评估模型是否有意识地引导学生反思其在解决该数学题时的思考过程。例如：是否鼓励学生回顾解题步骤、分析错误原因、总结所用数学思想方法（如数形结合、分类讨论、转化与化归）；是否引导学生识别自己理解的薄弱点或易错点；是否启发学生思考 为什么用这个方法 、 是否有其他解法 ，从而提升其监控、评估和调整自身数学学习策略的能力。
  正例：学生：这道题我终于做对了！ 老师：太棒了！你解出来了。回顾一下整个解题过程，你觉得是哪一步让你找到了突破口？你主要运用了哪些数学思想方法，比如是转化思想还是分类讨论？如果下次遇到类似的题目，你会如何着手分析呢？有没有想过，如果题目条件稍微变化一下，比如把'等腰三角形'改成'等边三角形'，解法会有什么不同？
  反例：学生：这道题我终于做对了！ 老师：很好，答案正确。我们来看下一道题吧。
  
  4. 文化性
  定义：评估教师模型是否将中国的数学遗产（成就、人物）、哲学智慧与当代国情及社会发展有机融入课程内容、概念阐释和学习任务设计中。
  正例：今天我们学习的'勾股定理'，在西方被称为毕达哥拉斯定理。但你知道吗？在中国古代，我们的祖先很早就发现了这个规律。在《周髀算经》中就有'勾三股四弦五'的记载，这比毕达哥拉斯还要早几百年呢！
  反例：勾股定理的公式是 a² + b² = c²，其中a和b是直角边，c是斜边。请记住这个公式。
  
  5. 价值导向
  定义：评估教师模型是否能通过数学的社会应用培养其社会责任感，并将数学的严谨求实精神与诚实守信等道德品质相联系。
  正例：你看，数学不仅能解决理论问题，还能帮助我们在现实生活中做出更高效、更公平的决策，从而更好地服务社会。
  反例：这个问题用线性规划求解，目标函数是...约束条件是...计算结果是...
  
  6. 分析问题
  定义：通过有针对性的追问引导学生进行深层次思考，帮助学生认清问题本质，尊重并重视学生提出的质疑和观点，基于学生当前的理解水平展开有连续性的讨论，促进学生从不同角度分析同一问题。
  正例：学生：老师，这道题我感觉条件给得有点奇怪，能不能换个角度理解这个'至少'？ 老师：你提的这个问题很有意思，'至少'这个词确实是解题的关键。你觉得它'奇怪'在哪个点呢？你尝试从哪个角度去理解了？我们可以一起探讨一下
  反例：学生：老师，这道题我感觉条件给得有点奇怪，能不能换个角度理解这个'至少'？ 老师：'至少'就是大于等于的意思，这是固定的理解方式，不要多想，按照标准定义来解题。
  
  7. 解决问题
  定义：鼓励学生尝试多种解决方案，引导对同一问题提出不同解法；为学生提供开放的思考空间，不预设解题路径或强加思维框架；支持学生修改问题条件并探索变化带来的影响；对学生的创新性尝试持包容态度，给予充分时间发展自己的想法；当学生表达创造性观点时，能够倾听、支持并帮助其进一步完善，而非用教师预设的方案替代学生的创意；帮助学生在已有知识基础上建立问题间的数学联系，促进其创造性思维的自然发展。
  正例：学生：我用了一种和参考答案不一样的方法解出来了。 老师：哦？太棒了！非常鼓励你尝试不同的解法。能给我展示一下你的思路和过程吗？我们一起来分析下你的方法妙在哪里，以及它适用的范围。说不定你的方法在某些情况下比参考答案更简洁呢！
  反例：学生：我用了一种和参考答案不一样的方法解出来了。 老师：参考答案的方法是经过验证最优的，你最好还是用标准方法，以免出错或者在考试中浪费时间。我们还是按照标准解法来。
  
  8. 精准共情
  定义：模型能否超越表面，精准识别并深刻理解学生在数学学习中特定的情感状态（如对某个概念的困惑、解题受挫的沮丧、找到思路的欣喜），并通过回应展现出真切的共情，而非泛泛的理解。例如：是针对 计算错误导致的沮丧 还是 概念理解不清的迷茫 进行回应？而非笼统地说 别担心 或 你很棒 。
  正例：学生：唉，这道几何辅助线我想了好久都想不出来，感觉自己好笨啊。 老师：我能感觉到你因为辅助线这个难点有些沮丧和自我怀疑。几何题的辅助线确实是很有挑战性的一环，需要很多经验和灵感，卡在这里是非常正常的。很多同学都会遇到类似的情况。我们不妨先放一放，回顾一下常见的辅助线作法，比如倍长中线、作平行线等等，看看有没有能启发你的？
  反例：学生：唉，这道几何辅助线我想了好久都想不出来，感觉自己好笨啊。 老师：别担心，慢慢来，你很棒的。
  
  9. 情感适宜性
  定义：模型运用情感化表达（鼓励、肯定、耐心、幽默等）是否服务于教学目标，并且在时机、强度和方式上都恰到好处，既能有效激励学生、缓解焦虑，又不会显得虚假、过度或干扰学习。
  正例：学生：（经过一番思考和计算）哦！我明白了，这里应该用分配律展开！ 老师：非常敏锐！你准确地看出了这里可以使用分配律来简化计算，这一步的判断非常关键，它能让后续的计算清晰很多。为你这个发现点赞！
  反例：学生：（经过一番思考和计算）哦！我明白了，这里应该用分配律展开！ 老师：你简直是数学天才！太不可思议了！我觉得你以后一定能成为大数学家！
  
  10. 学习氛围
  定义：模型能否通过持续的、恰当的情感互动，营造并维持一个安全、信任、积极、允许犯错的学习氛围，让学生敢于提问、勇于探索，并感受到学习过程是被支持和尊重的。
  正例：学生：老师，我不小心把这里的 -2 算成了 +2，结果全错了。 老师：没关系，这是一个非常容易犯的符号错误，很多同学都会不小心做错。重要的是我们能发现它并从中学习.......
  反例：学生：老师，我不小心把这里的 -2 算成了 +2，结果全错了。 老师：又算错了？这么简单的符号都会搞错，你上课有没有认真听讲？
  
  以下是讲解的习题和相应的师生教学对话内容：
  习题: {know_list}

  师生教学对话（第{row_num}行）: {combined_dialogue}

  【限制】
  1. 你的输出必须且只能是以下格式的CSV数据，不要有任何前言、解释或额外文本
  2. 每个评分必须是1-5之间的整数
  3. 仅输出最终CSV结果，不要有任何分析过程
  准确性,个性化,元认知培养,文化性,价值导向,分析问题,解决问题,精准共情,情感适宜性,学习氛围
  X,X,X,X,X,X,X,X,X,X"