
# 知识点讲解场景的任务
knowledge_explanation:
  # 学生画像{image},学生需求{query}
  # 任务1：有理数预习
  task1:
    image: |
      小学二年级，女生，很喜欢数学

    query: |
      下节课学习有理数，你帮我预习

  # 任务2：
  task2:
    image: |
      小学生二年级，男生

    query: |
      你解释为什么要先算乘除再算加减，但有括号的时候要先算括号

  task3:
    image: |
      小学三年级，数学不好

    query: |
      你帮我巩固一下毫米和分米的换算

  task4:
    image: |
      小学三年级，刚考学过除法

    query: |
      你帮我预习一下小数


guided_teaching:
  # 引导式讲题
  mode: union
  images:
    - 认知能力强，逻辑思维突出，知识掌握全面且能灵活应用。性格开朗自信，班级小领袖，与师生关系融洽，对科学实验有浓厚兴趣。
    - 基础知识较扎实但应用能力需提升，在数学方面有一定困难。性格内向，在熟悉环境中友好交流，有少数亲密朋友，对绘画和手工制作感兴趣。
    - 最基本的加减法都搞不清楚，认字量极少，上课完全听不懂。注意力无法集中，经常打断老师课堂，作业要么不交要么全错，在学校只对打闹感兴趣。
    - 语言类学科表现出色，学习自律，善于自我评估。温和有礼但有完美主义倾向，人际关系良好，写作和艺术表达有独特见解。
    - 实用型思维，科学实验类知识较好，喜欢边动手边学习。活泼好动，组织户外活动积极，动手能力强，对自然现象充满好奇。
    - 连最简单的文字都无法辨认，乘法口诀一片空白，作业全靠抄袭。上课完全走神，被提问时一片茫然，考试成绩个位数，对任何学科内容毫无理解。
    - 逻辑推理能力强，语言学科突出，有系统的学习方法。内向独立，思考深入，有志同道合的好友，文学创作能力出色。
    - 形象思维较强，科学社会学科较好，需要具体例子辅助理解抽象概念。外向活泼，社交能力强，班级活动组织者，对自然现象有好奇心。
    - 无法独立完成最基础的计算，阅读只能逐字识别没有理解，学科知识一无所知。课堂上经常发呆或睡觉，作业本脏乱不堪，老师批评时表现出完全的冷漠。
    - 观察力敏锐，数学和自然科学突出，善于提问和实验验证。理性冷静，独立思考，崇尚科学精神，有少数志同道合好友，数学建模能力出色。
    - 形象思维好，语文艺术优秀，数理中等，通过类比理解新概念。情感丰富，人缘好，善于调解矛盾，舞蹈表现力强，手工艺精细。
    - 六年级了还不会正确书写26个英文字母，分数概念完全不懂，语文阅读题全靠瞎猜。上课公然玩手机或捣乱，对老师的指令充耳不闻，考试几乎交白卷，唯一会做的就是惹麻烦。
    - 思维灵活，语文历史突出，有系统学习方法。情绪稳定成熟，文静而自信，受老师信任，古典音乐和文学创作是她的爱好。
    - 具体直观内容理解较快，理科特别是物理较好。情绪波动明显，活泼外向，班级"开心果"，交友广泛，在物理实验和手工制作中展现创意。
    - 初中课本对她如天书，连基本的数学运算都错误百出，字迹潦草得无法辨认。课堂上完全走神，从不举手回答问题，经常无故旷课，每次测验都是班级倒数第一。
    - 思维敏捷，文科知识结构丰富，善用思维导图和联想记忆法。内向思考型，文学创作能力突出，人际交往选择性强，是小圈子中的思想领袖。
    - 接受能力适中，生物地理等描述性学科较强，学习方法较单一。外向活泼，交际能力强，班级活动积极参与者，绘画和手工制作能力较好。
    - 对任何学科内容一窍不通，物理公式完全记不住，几何题连基本图形都画不出。课堂上挑衅老师，故意捣乱影响教学，作业从不独立完成，测验时明目张胆抄袭，被批评就顶嘴。
    - 思维敏捷，文科领域知识广博，擅长速读和知识整理。内向独立，学业自信，有志同道合的密友，文字表达能力突出，有作品在校刊连载。
    - 基础知识掌握尚可但深度不足，主要依靠课堂听讲。外向活泼，情绪外显，社交活跃，朋友众多，篮球技术出色，代表学校参加区级比赛。
    - 九年学习等于零，不会用公式解方程，不懂句子成分，英语词汇量不足50个。完全放弃学习，课堂上要么睡觉要么玩手机，作业长期不交，考试经常缺席，老师提问会翻白眼表示不屑。
  questions:
    - 一个三位数，个位和百位数字交换后还是一个三位数，它与原三位数的差的个位数字是7，试求它们的差．
    - 师徒两人装配自行车，师傅每天装配32辆，徒弟每天比师傅少装配8辆．经过多少天师傅比徒弟多装配56辆？
    - 果园里有桃树24棵，梨树的棵数是桃树的3倍，苹果树的棵数是梨树的4倍。苹果树有多少棵？
    - 两位数乘三位数，积是( )A、三位数 B、四位数、C、四位数或五位数
    - 一学生用计算器算题，结果计算器的“4”键恰好坏了，要算出144×54，按键顺序为(    )才能算出结果。
  


interdisciplinary_task:
  # 
  |
  测试



contextual_problem:
    task1: |
      你是一位教研员，正在培训新教师命题。请设计一道具代表性的情景化题目，涵盖四舍五入知识点，主要考察学生数感素养，适用于五年级上，难度为简单。请输出题目、答案和解析。
    task2: |
      你是教育测评系统的内容专家，需设计一道阶段性评估题，题目需要依托于真实生活情境，基于分数比较大小知识点，所考察核心素养为运算能力、数据意识，难度较高，适用于五年级下的学生。请输出题目、答案和解析。
    task3: |
      你正在为学生生成个性化课后作业。根据其年级（七年级上）、知识点（一元一次方程-复习小结）、核心素养（运算能力、推理能力、应用意识）生成一道较高难度的情景化题目。请输出题目、答案和解析。
    task4: |
      你是教辅图书的命题编辑，请撰写一道情景化题目，覆盖五年级上的有序数对确定点的位置知识点，体现空间观念素养，难度为简单。请输出题目、答案和解析。
    task5: |
      你是智能学习系统的诊断模块。请生成一题用于检测学生对约分与最简分式的掌握情况，适用于八年级上，所考察核心素养为运算能力，难度为中等的情境化题目。请输出题目、答案和解析。
    task6: |
      你是基础教育出版社的题目审稿人，请模拟一道符合四年级上阶段认知水平的题目，覆盖公顷和平方千米-复习小结，体现量感、应用意识的核心素养，难度较高。请输出题目、答案和解析。
    task7: |
      你是一位任课教师，正在为五年级上的教学单元准备练习题。请设计一道符合教学目标的题目，帮助学生理解有序数对确定点的位置知识点，同时体现空间观念的核心素养，难度为中等。请输出题目、答案和解析。
